FROM mirror.gcr.io/alpine:3

# Test disabled network access
RUN if curl -IsS www.google.com; then echo "Has network access!"; exit 1; fi

RUN cp -r /tmp/hermeto-output/deps/generic/ /deps

CMD ["ls", "-al", "/deps"]
