FROM mirror.gcr.io/node:18-alpine

# Test disabled network access
RUN if curl -IsS www.google.com; then echo "Has network access!"; exit 1; fi

WORKDIR /src

RUN . /tmp/hermeto.env && npm install && npm ls
