# SPDX-License-Identifier: GPL-3.0-only
import json

import pytest
from pyarn import lockfile  # type: ignore

from hermeto.core.errors import PackageRejected
from hermeto.core.package_managers.common import PackageJson
from hermeto.core.package_managers.yarn_classic.main import _verify_repository
from hermeto.core.package_managers.yarn_classic.project import Project, YarnLock
from hermeto.core.rooted_path import RootedPath

VALID_PACKAGE_JSON_FILE = """
{
  "name": "camelot",
  "packageManager": "yarn@3.6.1"
}
"""

PNP_PACKAGE_JSON_FILE = """
{
  "name": "camelot",
  "packageManager": "yarn@3.6.1",
  "installConfig": {
    "pnp": true
  }
}
"""

INVALID_JSON_FILE = "totally not json"

VALID_YARN_LOCK_FILE = """
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
package-1@^1.0.0:
  version "1.0.3"
  resolved "https://registry.npmjs.org/package-1/-/package-1-1.0.3.tgz#a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0"
"""

EMPTY_YARN_LOCK_FILE = """

"""

INVALID_YARN_LOCK_FILE = """
# yarn lockfile v1
package-1
  version "1.0.3"
"""


def _write_file(rooted_tmp_path: RootedPath, filename: str, content: str) -> RootedPath:
    path = rooted_tmp_path.join_within_root(filename)
    path.path.write_text(content)
    return path


def _setup_pnp_installs(rooted_tmp_path: RootedPath, pnp_kind: str) -> None:
    if pnp_kind == "node":
        rooted_tmp_path.join_within_root("node_modules").path.mkdir()
    if pnp_kind == "pnp_cjs":
        rooted_tmp_path.join_within_root("foo.pnp.cjs").path.touch()


def test_package_json_config_file_attributes(rooted_tmp_path: RootedPath) -> None:
    path = _write_file(rooted_tmp_path, "package.json", VALID_PACKAGE_JSON_FILE)
    package_json = PackageJson.from_file(path.path)
    assert package_json.path == rooted_tmp_path.path / "package.json"


def test_yarnlock_config_file_attributes(rooted_tmp_path: RootedPath) -> None:
    path = _write_file(rooted_tmp_path, "yarn.lock", VALID_YARN_LOCK_FILE)
    yarn_lock = YarnLock.from_file(path)
    assert yarn_lock.path.root == rooted_tmp_path.root


def test_package_json_find_and_open_config_file(rooted_tmp_path: RootedPath) -> None:
    path = _write_file(rooted_tmp_path, "package.json", VALID_PACKAGE_JSON_FILE)
    package_json = PackageJson.from_file(path.path)
    assert package_json.data == json.loads(VALID_PACKAGE_JSON_FILE)


def test_yarnlock_find_and_open_config_file(rooted_tmp_path: RootedPath) -> None:
    path = _write_file(rooted_tmp_path, "yarn.lock", VALID_YARN_LOCK_FILE)
    yarn_lock = YarnLock.from_file(path)
    assert yarn_lock.data == lockfile.Lockfile.from_str(VALID_YARN_LOCK_FILE).data


def test_package_json_from_file_bad(rooted_tmp_path: RootedPath) -> None:
    path = _write_file(rooted_tmp_path, "package.json", INVALID_JSON_FILE)
    with pytest.raises(PackageRejected):
        PackageJson.from_file(path.path)


def test_yarnlock_from_file_empty(rooted_tmp_path: RootedPath) -> None:
    path = _write_file(rooted_tmp_path, "yarn.lock", EMPTY_YARN_LOCK_FILE)
    with pytest.raises(PackageRejected):
        YarnLock.from_file(path)


def test_yarnlock_from_file_invalid(rooted_tmp_path: RootedPath) -> None:
    path = _write_file(rooted_tmp_path, "yarn.lock", INVALID_YARN_LOCK_FILE)
    with pytest.raises(PackageRejected):
        YarnLock.from_file(path)


def test_package_json_from_file_missing(rooted_tmp_path: RootedPath) -> None:
    with pytest.raises(PackageRejected):
        path = rooted_tmp_path.join_within_root("package.json")
        PackageJson.from_file(path.path)


def test_yarnlock_from_file_missing(rooted_tmp_path: RootedPath) -> None:
    with pytest.raises(PackageRejected):
        path = rooted_tmp_path.join_within_root("yarn.lock")
        YarnLock.from_file(path)


@pytest.mark.parametrize(
    "content, pnp_kind",
    [
        pytest.param(PNP_PACKAGE_JSON_FILE, "install_config", id="installConfig"),
        pytest.param(VALID_PACKAGE_JSON_FILE, "node", id="node"),
        pytest.param(VALID_PACKAGE_JSON_FILE, "pnp_cjs", id="pnp_cjs"),
    ],
)
def test_pnp_installs_true(
    rooted_tmp_path: RootedPath,
    content: str,
    pnp_kind: str,
) -> None:
    _write_file(rooted_tmp_path, "package.json", content)

    project = Project.from_source_dir(rooted_tmp_path)

    _setup_pnp_installs(rooted_tmp_path, pnp_kind)
    with pytest.raises(PackageRejected):
        _verify_repository(project)


def test_pnp_installs_false(rooted_tmp_path: RootedPath) -> None:
    _write_file(rooted_tmp_path, "package.json", VALID_PACKAGE_JSON_FILE)
    _write_file(rooted_tmp_path, "yarn.lock", VALID_YARN_LOCK_FILE)

    project = Project.from_source_dir(rooted_tmp_path)

    _verify_repository(project)
