FROM mirror.gcr.io/node:17-alpine

# Test disabled network access
RUN if curl -IsS www.google.com; then echo "Has network access!"; exit 1; fi

WORKDIR /src/first_pkg
RUN . /tmp/hermeto.env && npm install && npm ls

WORKDIR /src/second_pkg
RUN . /tmp/hermeto.env && npm install && npm ls
