FROM mirror.gcr.io/node:18.19.0-alpine

# Test disabled network access
RUN if curl -IsS www.google.com; then echo "Has network access!"; exit 1; fi

WORKDIR /src
RUN . /tmp/hermeto.env && yarn install --mode skip-build && yarn build

# During the build, the source code is only mounted, not copied
# Some integration tests use CMD that requires the source code to be present
RUN cp -r /src /app
WORKDIR /app
