FROM mirror.gcr.io/rust:1.85-slim

# Test disabled network access
RUN if curl -IsS www.google.com; then echo "Has network access!"; exit 1; fi

WORKDIR /src
RUN cargo install --frozen --path .

ENTRYPOINT ["rustic"]
